### PR TITLE
Clamp pointer position to work-area before edge-tiling

### LINKED ISSUE #108: Extend edge tiling detection to panel areas
**Describe the bug**

The Tiling Shell does not detect tiling regions for drags outside the `workArea` of a monitor, e.g. drags in the area occupied by any shell panel.

**To Reproduce (Mouse movement too fast)**

1. Flick a window over the top-center edge tiling area of the screen to maximize it, so that the mouse stops on the top panel.

This does not function as intended if the mouse moves too fast, where the `EdgeTilingManager`'s `startEdgeTiling` function is never called for the `_topCenter` rectangle.

**To Reproduce (Drag along the panel)**

1. Drag a window over the top-center edge tiling area onto the top panel. (The edge tiling preview shows the maximized window)
2. Drag the mouse along the panel to the left or right corner. (The edge tiling preview does not update the region)

The `EdgeTilingManager` treats all panels beyond the working area as `changed: false` cases. See https://github.com/domferr/tilingshell/blob/c3a24061325dca5d38ddfb1cda8897acb2c269e3/src/components/tilingsystem/edgeTilingManager.ts#L173-L176

**Additional Context** 

I think that the tiling code should calculate the edge-tiling and snap-assist detection using a combination of both the monitors actual geometry (`Main.layoutManager.monitors[index]`) and the workArea when dragging a window. The `TilingManager` is already aware of the actual `_monitor` and uses it's real geometry in `_isPointerInsideThisMonitor`. But the `EdgeTilingManager` and `SnapAssist` don't handle mouse movements on panels properly.

A simple solution might be to clamp the x and y pointer coordinates to the workArea before passing them to the `EdgeTilingManager` or `SnapAssist`. Another solution might be to extend the rectangles used for detection (e.g. `_topCenter`/`_topLeft`/...) to the actual edges of the monitor instead of the edges of the workArea.

**Information (please complete the following):**
 - Tiling Shell version: v11.1 and v12
 - GNOME version: 46

### PR DESCRIPTION
**Pull request by PJungkamp**
Fixes #108 by clamping the pointer position to the `EdgeTilingManager`'s `_workArea` so that edge tiling also works when dragging the window on panels.

See #108 for more information!

### CODE REVIEW

**Comment by domferr** [comment]
Hey! Thank you for the pull request and for solving the issue! It seems promising, I'm writing the review so we can merge this asap! I'd like to merge to branch v12.1, which is the next release's branch. That is a minor release that will be published this week.

Speaking about your pull request, since I haven't access to a multi monitor setup I'm not able to test it with that particular case. Do you have one and can confirm the changes are working with that setup too? Thank you!

File: src/components/tilingsystem/edgeTilingManager.ts [hunk 1]
```diff
@@ -81,12 +81,14 @@ export default class EdgeTilingManager {
...
-    public canActivateEdgeTiling(x: number, y: number) {
+    public canActivateEdgeTiling(
+        pointerPos: { x: number; y: number }
+    ): boolean {
         return (
-            x <= this._workArea.x + EDGE_TILING_OFFSET ||
-            y <= this._workArea.y + TOP_EDGE_TILING_OFFSET ||
-            x >= this._workArea.x + this._workArea.width - EDGE_TILING_OFFSET ||
-            y >= this._workArea.y + this._workArea.height - EDGE_TILING_OFFSET
+            pointer.x <= this._workArea.x + EDGE_TILING_OFFSET ||
```
Comment (domferr) [inline src/components/tilingsystem/edgeTilingManager.ts:88]: The extension stops working here because pointer is undefined. That's clearly a typo (`pointer` instead of `pointerPos`).
After fixing it, I was able to test your changes.

Comment (PJungkamp) [reply src/components/tilingsystem/edgeTilingManager.ts:88]: Stupid last minute fixups.... I'll make it right and test it with multiple monitors.

**Review by domferr — COMMENTED** [review]
Nice work! I can confirm it is working on my system (GNOME 44) very well. Clamping each time doesn't seem to affect performances and I like how you solved the problem. Thank you

**Comment by PJungkamp** [comment]
Multiple monitors are also working nicely!

**Comment by PJungkamp** [comment]
I'll autosquash the fixup commit if you're satisfied!

**Comment by domferr** [comment]
Woohoo! :partying_face: 

Oh yes, thank you!

**Comment by domferr** [comment]
@PJungkamp If that's ok for you, I'd like to cite you by linking your github profile in the next release notes, in the entry about the changes you made. Let me know :smile:

**Comment by PJungkamp** [comment]
Of course! You can also tag me if you need some testing on multi-monitor, mixed-refresh-rate, mixed-scaling, mixed-resolution setups.

**Comment by domferr** [comment]
> Of course! You can also tag me if you need some testing on multi-monitor, mixed-refresh-rate, mixed-scaling, mixed-resolution setups.

Awesome! Thanks a million :heart:
